(TeX-add-style-hook
 "adfib_notes"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "adfib_preamble"
    "amsart"
    "amsart10")
   (LaTeX-add-labels
    "sec:preliminaries"
    "lem:Lack1"
    "eq:13"
    "eq:opfibration"
    "factor"
    "reindexing"
    "lem:fibrewiselimits"
    "it:2"
    "prop:coreflection"
    "sec:groth-fibs-ralis"
    "prop:opfibtolari"
    "prop:laritoopfib"
    "thm:mainthm"
    "Streetfibs"
    "thm:street-opfib-to-corefl"
    "thm:corefl-to-street-obfib"
    "thm:main-theorem-street-version")
   (LaTeX-add-bibliographies
    "references"))
 :latex)

